Repository PawSeul/PawSeul, pull requests merged in 2024-11, with the labels that each got.

#58 [feat(be)] 장바구니 상품 수정
  backend/src/cart/cart.controller.ts
  backend/src/cart/cart.service.ts
  backend/src/cart/dto/addProductCart.dto.ts
  backend/src/cart/dto/updateProductCart.dto.ts
Labels: BE, feat

#59 [feat(be)] 장바구니 원하는 상품 삭제
  backend/src/cart/cart.controller.ts
  backend/src/cart/cart.service.ts
  backend/src/cart/dto/deleteProduct.dto.ts
  backend/src/entity/cart.product.entity.ts
Labels: BE, feat

#61 [refact] 장바구니 조회 품목 수정
  backend/src/cart/cart.service.ts
  backend/src/cart/dto/CartItem.dto.ts
  backend/src/cart/dto/getCartsResponse.dto.ts
  backend/src/entity/cart.product.entity.ts
  backend/src/entity/product.entity.ts
Labels: BE, refactor

#62 [refact] 장바구니 update 요청 방식 수정
  backend/src/cart/cart.controller.ts
Labels: BE, refactor

#63 [refact]mypage 반환값 수정
  backend/src/mypage/dto/getUserResponse.dto.ts
  backend/src/mypage/mypage.controller.ts
  backend/src/mypage/mypage.service.ts
Labels: BE, refactor

#67 [feat] 장바구니 Empty UI 추가, 전역 상태 관리 적용
  frontend/public/svgs/cart_empty.svg
  frontend/public/svgs/cart_empty_black.svg
  frontend/src/apis/getSearchList.ts
  frontend/src/assets/images/svgs/CartEmpty.tsx
  frontend/src/assets/images/svgs/CartEmptyBlack.tsx
  frontend/src/assets/images/svgs/index.tsx
  frontend/src/assets/types/CartType.tsx
  frontend/src/components/cart/CartCost/index.tsx
  frontend/src/components/cart/CartItem/index.tsx
  frontend/src/components/cart/Checkbox/index.tsx
  frontend/src/mocks/data/cart.json
  frontend/src/mocks/handler.ts
  frontend/src/pages/Cart/index.tsx
  frontend/src/pages/Store/Detail.tsx
  frontend/src/stores/cartStore.ts
Labels: FE, feat

#68 [refact]마이페이지 반환값 수정
  backend/src/mypage/mypage.controller.ts
  backend/src/mypage/mypage.service.ts
Labels: BE, refactor

#70 [fix] 마이페이지 dto 파일 추가
  backend/src/mypage/dto/getUserResponse.dto.ts
Labels: BE, fix

#73 [feat] payment UI 수정, 토스페이먼츠 연동, StickyFooter 수정
  backend/yarn.lock
  frontend/package.json
  frontend/public/svgs/Toss_Logo.svg
  frontend/src/App.tsx
  frontend/src/apis/client.ts
  frontend/src/apis/getMypageInfo.ts
  frontend/src/apis/getProductList.ts
  frontend/src/assets/images/svgs/TossLogo.tsx
  frontend/src/assets/images/svgs/index.tsx
  frontend/src/assets/types/OrderType.ts
  frontend/src/assets/types/ProductType.tsx
  frontend/src/assets/types/ProfileType.ts
  frontend/src/components/common/Button/Button.tsx
  frontend/src/components/home/Card.tsx
  frontend/src/components/mypage/orderHistory/index.tsx
  frontend/src/components/mypage/orderHistory/orderContent.tsx
  frontend/src/components/mypage/profile/index.tsx
  frontend/src/components/mypage/profile/profile.stories.tsx
  frontend/src/components/store/Product/Product.stories.tsx
  frontend/src/components/store/Product/ProductHorizontal.stories.tsx
  frontend/src/components/store/Product/ProductHorizontal.tsx
  frontend/src/components/store/Product/index.tsx
  frontend/src/components/store/Select/index.tsx
  frontend/src/components/store/StickyFooter/index.tsx
  frontend/src/main.tsx
  frontend/src/mocks/data/user_order.json
  frontend/src/mocks/data/user_reviews_done.json
  frontend/src/mocks/data/user_reviews_remain.json
  frontend/src/pages/Home.tsx
  frontend/src/pages/Mypage/index.tsx
  frontend/src/pages/Payment/Fail.tsx
  frontend/src/pages/Payment/Success.tsx
  frontend/src/pages/Payment/TossPayment.tsx
  frontend/src/pages/Payment/index.tsx
  frontend/src/pages/Store/index.tsx
  frontend/yarn.lock
Labels: FE, feat, style

#75 feat: getProductList reactQuery 적용(LUP-22)
  frontend/src/apis/common/user.ts
  frontend/src/apis/getCartList.ts
  frontend/src/apis/getProductList.ts
  frontend/src/apis/getTopProductLis.ts
  frontend/src/apis/getUserReviewDone.ts
  frontend/src/apis/getUserReviewRemain.ts
  frontend/src/apis/hooks/useCartQuery.ts
  frontend/src/apis/hooks/useProductList.ts
  frontend/src/pages/Mypage/index.tsx
  frontend/src/pages/Store/index.tsx
Labels: FE, feat

#76 [feat] review 및 order api 추가
  backend/package.json
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/configs/setupSwagger.ts
  backend/src/entity/order.entity.ts
  backend/src/entity/orderItem.entity.ts
  backend/src/entity/productReview.entity.ts
  backend/src/order/dto/orderItem.dto.ts
  backend/src/order/dto/orderListResponse.dto.ts
  backend/src/order/order.controller.ts
  backend/src/order/order.module.ts
  backend/src/order/order.service.ts
  backend/src/product/product.controller.ts
  backend/src/product/product.service.ts
  backend/src/review/review.controller.ts
  backend/src/review/review.service.ts
  backend/src/types/category.ts
  backend/src/types/order.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
Labels: BE, feat

#78 [feat]리뷰할 상품 조회
  backend/src/order/order.controller.ts
  backend/src/order/order.module.ts
  backend/src/order/order.service.ts
Labels: BE, feat

#79 [fix] 장바구니 상품 수정 및 삭제 수정
  backend/src/cart/cart.service.ts
Labels: BE, fix

#81 [feat] 작성한 리뷰 리스트 api 추가
  backend/.yarn/install-state.gz
  backend/package.json
  backend/src/auth/strategies/accessToken.strategy.ts
  backend/src/entity/pet.entity.ts
  backend/src/entity/product.entity.ts
  backend/src/entity/productReview.entity.ts
  backend/src/entity/user.entity.ts
  backend/src/order/dto/myReviewsRequest.dto.ts
  backend/src/order/order.controller.ts
  backend/src/order/order.service.ts
  backend/src/review/dto/getMyReviewsResponse.dto.ts
  backend/src/review/review.controller.ts
  backend/src/review/review.module.ts
  backend/src/review/review.service.ts
  backend/yarn.lock
Labels: BE, feat

#82 [refact] 토큰값으로 리뷰 불러오기
  backend/src/order/order.controller.ts
Labels: BE, refactor

#83 [feat] TOP10 상품 조회
  backend/src/entity/product.entity.ts
  backend/src/product/product.controller.ts
  backend/src/product/product.module.ts
  backend/src/product/product.service.ts
Labels: BE, feat

#84 [refact] 반환값 수정
  backend/src/order/order.service.ts
Labels: BE, refactor

#85 [refact] change return value
  backend/src/order/order.controller.ts
  backend/src/order/order.service.ts
Labels: BE, refactor

#90 [feat] payment modal
  frontend/package.json
  frontend/src/apis/hooks/cart.tsx
  frontend/src/apis/hooks/review.tsx
  frontend/src/components/Address/index.tsx
  frontend/src/components/common/Modal/Modal.tsx
  frontend/src/components/store/StickyFooter/index.tsx
  frontend/src/components/store/detail/ProductReview.tsx
  frontend/src/pages/Cart/index.tsx
  frontend/src/pages/Payment/index.tsx
  frontend/src/pages/Store/Detail.tsx
  frontend/yarn.lock
Labels: FE, feat

#93 [feat] 결제 및 order 관련 api 추가
  backend/src/cart/cart.service.ts
  backend/src/configs/setupSwagger.ts
  backend/src/entity/cart.product.entity.ts
  backend/src/entity/order.entity.ts
  backend/src/entity/orderItem.entity.ts
  backend/src/entity/productReview.entity.ts
  backend/src/order/dto/PartialOrderItem.dto.ts
  backend/src/order/dto/confirmOrderResponse.dto.ts
  backend/src/order/dto/tempOrderRequest.dto.ts
  backend/src/order/order.controller.ts
  backend/src/order/order.module.ts
  backend/src/order/order.service.ts
  backend/src/pet/dto/petInfo.dto.ts
  backend/src/review/dto/review.dto.ts
  backend/src/review/review.controller.ts
  backend/src/review/review.service.ts
Labels: BE, feat

#95 [refact] null 값 유효성 검사
  backend/src/cart/cart.controller.ts
  backend/src/cart/dto/addProductCart.dto.ts
  backend/src/cart/dto/deleteProduct.dto.ts
  backend/src/cart/dto/updateProductCart.dto.ts
  backend/src/mypage/dto/updatePetRequest.dto.ts
  backend/src/mypage/mypage.controller.ts
  backend/src/order/dto/tempOrderRequest.dto.ts
  backend/src/order/order.controller.ts
  backend/src/pet/dto/petInfo.dto.ts
  backend/src/pet/pet.controller.ts
  backend/src/review/review.controller.ts
Labels: BE, refactor

#96 [feat] 반려견 정보 수정
  frontend/src/App.tsx
  frontend/src/apis/getMypageInfo.ts
  frontend/src/apis/getProductList.ts
  frontend/src/apis/hooks/mypage.tsx
  frontend/src/apis/mypage.tsx
  frontend/src/components/Address/index.tsx
  frontend/src/components/mypage/profile/index.tsx
  frontend/src/pages/Mypage/Modify.tsx
  frontend/src/pages/Mypage/index.tsx
  frontend/src/pages/Payment/index.tsx
  frontend/src/pages/Signup/Result.tsx
Labels: FE, feat, style

#97 [fix] 모듈 추가
  backend/package.json
  backend/src/main.ts
Labels: BE, fix

#98 [feat] 결제 api 연동 및 수정
  backend/src/cart/cart.module.ts
  backend/src/cart/cart.service.ts
  backend/src/order/dto/tempOrderRequest.dto.ts
  backend/src/order/order.controller.ts
  backend/src/order/order.module.ts
  backend/src/order/order.service.ts
  backend/src/product/product.service.ts
  frontend/src/apis/order.tsx
  frontend/src/assets/types/OrderType.ts
  frontend/src/pages/Payment/Fail.tsx
  frontend/src/pages/Payment/Success.tsx
  frontend/src/pages/Payment/TossPayment.tsx
Labels: BE, feat

#101 [feat] updateAverageScore 메소드 추가
  backend/src/product/product.service.ts
  backend/src/review/review.module.ts
  backend/src/review/review.service.ts
Labels: BE, feat

#102 [fix] 비동기 함수 관련 코드 수정
  backend/src/mypage/dto/updatePetRequest.dto.ts
  frontend/src/apis/hooks/mypage.tsx
  frontend/src/apis/hooks/user.tsx
  frontend/src/pages/Mypage/Modify.tsx
  frontend/src/pages/Mypage/index.tsx
Labels: FE, fix

#103 [feat] 건강 api 추가
  backend/.yarn/install-state.gz
  backend/package.json
  backend/src/app.module.ts
  backend/src/health/dto/aiHealthReponse.dto.ts
  backend/src/health/dto/aiHealthRequest.dto.ts
  backend/src/health/health.controller.ts
  backend/src/health/health.module.ts
  backend/src/health/health.service.ts
  backend/src/product/product.service.ts
  backend/yarn.lock
Labels: BE, feat

#106 [chore] z-index 수정
  frontend/src/components/common/Modal/Modal.tsx
Labels: FE, chore

#108 [feat] health api 및 리뷰 작성해야 하는 물품 api 수정
  backend/src/entity/health.entity.ts
  backend/src/health/health.controller.ts
  backend/src/health/health.module.ts
  backend/src/health/health.service.ts
  backend/src/order/order.controller.ts
  backend/src/review/review.controller.ts
  backend/src/review/review.service.ts
Labels: BE, fix, feat

#107 [feat] 장바구니 수정, 삭제 API 연결
  frontend/src/apis/hooks/useCartQuery.ts
  frontend/src/components/cart/CartItem/index.tsx
  frontend/src/pages/Cart/index.tsx
  frontend/src/stores/cartStore.ts
Labels: FE, feat, chore

#111 [feat] 주문 취소 기능 구현 , 마이페이지 리뷰 모달 연결
  frontend/src/apis/hooks/order.tsx
  frontend/src/apis/hooks/useUserReview.ts
  frontend/src/apis/order.tsx
  frontend/src/components/mypage/orderHistory/orderContent.tsx
  frontend/src/components/store/detail/ProductReview.tsx
  frontend/src/pages/Mypage/Order.tsx
  frontend/src/pages/Mypage/Review.tsx
Labels: FE, feat

#114 [fix] 주문 내역에 결제 취소 출력 및 건강 진단 api에 recommand product 추가
  backend/.gitignore
  backend/src/auth/auth.controller.ts
  backend/src/entity/recommandProduct.entity.ts
  backend/src/health/dto/recommandProduct.dto.ts
  backend/src/health/health.module.ts
  backend/src/health/health.service.ts
  backend/src/order/order.service.ts
Labels: BE, fix, feat

#116 [feat] Search API 연결 및 기능 구현, header 공통 컴포넌트 수정, Detail 페이지 header 연결
  frontend/public/svgs/notFound.svg
  frontend/src/apis/getSearchList.ts
  frontend/src/assets/images/svgs/NotFound.tsx
  frontend/src/assets/images/svgs/index.tsx
  frontend/src/components/common/Header/index.tsx
  frontend/src/components/search/RecentSearchResult.tsx
  frontend/src/components/search/SearchResult.tsx
  frontend/src/components/store/detail/ProductReview.tsx
  frontend/src/pages/Search/index.tsx
  frontend/src/pages/Store/Detail.tsx
Labels: FE, refactor, feat, style

#117 [fix] 백엔드 버그 fix 및 다중 cart 삭제 api로 카드 물품 삭제 수정
  backend/src/cart/cart.controller.ts
  backend/src/cart/cart.service.ts
  backend/src/cart/dto/deleteProduct.dto.ts
  backend/src/configs/typeorm.config.ts
  backend/src/entity/health.entity.ts
  backend/src/entity/pet.entity.ts
  backend/src/entity/recommandProduct.entity.ts
  backend/src/health/dto/aiHealthReponse.dto.ts
  backend/src/health/dto/recommandProduct.dto.ts
  backend/src/health/health.module.ts
  backend/src/health/health.service.ts
  backend/src/order/order.service.ts
Labels: BE, fix, feat

#115 [feat] 홈화면 건강분석 이력 UI 추가 구현
  backend/yarn.lock
  frontend/public/svgs/mypage_icon.svg
  frontend/src/apis/getCartList.ts
  frontend/src/apis/getProductDetail.ts
  frontend/src/apis/getProductList.ts
  frontend/src/apis/getTopProductLis.ts
  frontend/src/apis/health.tsx
  frontend/src/apis/hooks/health.tsx
  frontend/src/apis/hooks/product.tsx
  frontend/src/apis/hooks/useCartQuery.ts
  frontend/src/apis/hooks/useProductDetailQuery.ts
  frontend/src/apis/hooks/useProductList.ts
  frontend/src/apis/order.tsx
  frontend/src/apis/product.tsx
  frontend/src/assets/images/lotties/PaymentLoading.json
  frontend/src/assets/images/svgs/KeyboardArrowRight.jsx
  frontend/src/assets/images/svgs/index.tsx
  frontend/src/assets/types/ProductType.tsx
  frontend/src/components/health/Loading.tsx
  frontend/src/components/home/HealthHistory.tsx
  frontend/src/components/mypage/orderHistory/index.tsx
  frontend/src/components/mypage/profile/index.tsx
  frontend/src/components/payment/PaymentLoading.tsx
  frontend/src/components/store/Product/index.tsx
  frontend/src/components/store/Select/index.tsx
  frontend/src/pages/Health/Result.tsx
  frontend/src/pages/Health/index.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Mypage/Modify.tsx
  frontend/src/pages/Mypage/Order.tsx
  frontend/src/pages/Mypage/Review.tsx
  frontend/src/pages/Mypage/index.tsx
  frontend/src/pages/Payment/Fail.tsx
  frontend/src/pages/Payment/Success.tsx
  frontend/src/pages/Payment/index.tsx
  frontend/src/pages/Store/Detail.tsx
  frontend/src/stores/cartStore.ts
Labels: FE, refactor, feat

#119 fix: hook 코드 수정(LUP-131)
  frontend/src/apis/health.tsx
  frontend/src/apis/hooks/health.tsx
  frontend/src/components/health/Loading.tsx
  frontend/src/components/health/Recommend.tsx
  frontend/src/components/home/HealthHistory.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Store/index.tsx
Labels: FE, fix, style

#120 [feat] Skeleton ui 추가 및 백엔드 버그 수정
  backend/src/cart/dto/deleteProduct.dto.ts
  backend/src/health/health.service.ts
  frontend/src/components/skeleton/Skeleton.stories.tsx
  frontend/src/components/skeleton/Skeleton.tsx
  frontend/src/components/skeleton/index.tsx
  frontend/src/pages/Store/index.tsx
Labels: FE, BE, feat

#121 [fix] 스타일 수정 및 mypage review 코드 오류 수정, console log 제거
  frontend/src/apis/getSearchList.ts
  frontend/src/apis/hooks/order.tsx
  frontend/src/apis/hooks/product.tsx
  frontend/src/apis/hooks/useUserReview.ts
  frontend/src/apis/mypage.tsx
  frontend/src/apis/order.tsx
  frontend/src/apis/product.tsx
  frontend/src/components/home/Card.tsx
  frontend/src/components/mypage/orderHistory/index.tsx
  frontend/src/components/mypage/orderHistory/orderContent.tsx
  frontend/src/components/mypage/profile/index.tsx
  frontend/src/components/payment/Address.tsx
  frontend/src/components/store/detail/ProductReview.tsx
  frontend/src/pages/Health/Result.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Mypage/Order.tsx
  frontend/src/pages/Mypage/Review.tsx
  frontend/src/pages/Mypage/index.tsx
  frontend/src/pages/Payment/TossPayment.tsx
  frontend/src/pages/Store/Detail.tsx
  frontend/src/pages/Store/index.tsx
  frontend/src/utils/tableData.ts
Labels: FE, fix, style

#122 [fix] bug-fix
  backend/src/order/order.service.ts
  backend/src/review/review.module.ts
  backend/src/review/review.service.ts
Labels: BE, bug, fix

#125 [chore] 프론트엔드 github action 추가
  .github/workflows/frontend-prod-cd.yml
Labels: FE, chore

#129 [fix] store, detail페이지 UI 및 기능 수정
  frontend/src/components/cart/Checkbox/index.tsx
  frontend/src/components/common/Header/index.tsx
  frontend/src/components/mypage/orderHistory/index.tsx
  frontend/src/components/mypage/profile/index.tsx
  frontend/src/components/search/SearchResult.tsx
  frontend/src/components/store/detail/ProductReview.tsx
  frontend/src/components/store/detail/ProductReviewItem.tsx
  frontend/src/pages/Cart/index.tsx
  frontend/src/pages/Store/Detail.tsx
Labels: FE, chore, style

#130 [fix] ai 추천 물품 중복 금지 추가
  backend/src/health/health.service.ts
Labels: BE, fix

#132 [fix] 홈 화면 averageScore 반영
  frontend/src/pages/Home.tsx
Labels: FE, fix

#133 [hotfix] 글자 오류 수정
  frontend/src/components/home/HealthHistory.tsx
Labels: FE, style

#135 [hotfix] 오타 수정
  backend/src/entity/recommendProduct.entity.ts
  backend/src/health/dto/aiHealthReponse.dto.ts
  backend/src/health/dto/recommendProduct.dto.ts
  backend/src/health/health.module.ts
  backend/src/health/health.service.ts
  backend/src/mypage/mypage.controller.ts
  frontend/src/apis/health.tsx
  frontend/src/apis/hooks/cart.tsx
  frontend/src/apis/hooks/order.tsx
  frontend/src/apis/hooks/review.tsx
  frontend/src/assets/images/svgs/CloseIcon/WhiteCloseIcon.tsx
  frontend/src/assets/images/svgs/CloseIcon/index.tsx
  frontend/src/components/health/CurFood.tsx
  frontend/src/components/health/Loading.tsx
  frontend/src/components/health/Recommend.tsx
  frontend/src/components/home/HealthHistory.tsx
  frontend/src/components/mypage/orderHistory/index.tsx
  frontend/src/components/payment/Address.tsx
  frontend/src/components/search/SearchResult.tsx
  frontend/src/pages/Health/Result.tsx
  frontend/src/pages/Payment/Success.tsx
  frontend/src/pages/Payment/index.tsx
  frontend/src/pages/Search/index.tsx
  frontend/src/pages/Store/Detail.tsx
Labels: FE, BE, fix, feat

#137 [chore] 주석 처리
  backend/src/health/health.module.ts
Labels: FE, BE
