Repository PawSeul/PawSeul, pull requests merged in 2024-10, with the labels that each got.

#3 [feat]프론트엔드 개발 초기 세팅
  backend/.eslintrc.js
  backend/.gitignore
  backend/.prettierrc
  backend/.yarn/install-state.gz
  backend/README.md
  backend/nest-cli.json
  backend/package.json
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/main.ts
  backend/tsconfig.build.json
  backend/tsconfig.json
  backend/yarn.lock
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/apis/client.ts
  frontend/src/components/common/Header/Header.stories.tsx
  frontend/src/components/common/Header/index.tsx
  frontend/src/components/common/Layout/index.tsx
  frontend/yarn.lock
Labels: FE, feat

#4 [Init]벡엔드 개발 초기 세팅
  .github/workflows/backend-prod-cd.yml
  .gitignore
  .prettierrc
  backend/.dockerignore
  backend/.gitignore
  backend/.yarn/install-state.gz
  backend/Dockerfile
  backend/configs/setupSwagger.ts
  backend/configs/typeorm.config.ts
  backend/package.json
  backend/src/app.module.ts
  backend/src/main.ts
  backend/yarn.lock
  frontend/.prettierrc
  package.json
  yarn.lock
Labels: BE, infra

#5 [Init] configs 폴더 위치 변경
  backend/src/app.module.ts
  backend/src/configs/setupSwagger.ts
  backend/src/configs/typeorm.config.ts
  backend/src/main.ts
Labels: BE, fix, infra

#6 [feat(fe)] Login 기본 UI 및 component 생성
  frontend/src/App.tsx
  frontend/src/components/Login/PetAdd.tsx
  frontend/src/components/common/Header/index.tsx
  frontend/src/components/common/Layout/index.tsx
  frontend/src/pages/Login.tsx
  frontend/tsconfig.app.json
Labels: FE, feat

#8 [chore] typo 설정 수정
  frontend/src/styles/typo.tsx
Labels: FE, chore

#10 [feat] style 수정 및 로그인 기능 수정
  frontend/src/App.tsx
  frontend/src/assets/images/pngs/kakao_login_medium_wide.png
  frontend/src/components/Login/PetAdd.tsx
  frontend/src/pages/Login.tsx
  frontend/src/styles/PetAddStyles.ts
Labels: FE, feat

#12 [feat] food, snack, suppplement-entity
  backend/src/entity/food.entity.ts
  backend/src/entity/snack.entity.ts
  backend/src/entity/supplement.entity.ts
Labels: BE, feat

#15 [feat] Product, Star Component 및 Store Page UI 추가
  frontend/package.json
  frontend/src/assets/types/ProductType.tsx
  frontend/src/components/common/Layout/index.tsx
  frontend/src/components/common/Typo/index.tsx
  frontend/src/components/store/Product/Product.stories.tsx
  frontend/src/components/store/Product/index.tsx
  frontend/src/components/store/Star/Star.stories.tsx
  frontend/src/components/store/Star/index.tsx
  frontend/src/mocks/data/snack.json
  frontend/src/pages/Store/index.tsx
  frontend/src/styles/typo.tsx
  frontend/yarn.lock
Labels: FE, feat

#18 [feat] 상품 상세 페이지 레이아웃 및 설명 더보기 버튼 구현
  frontend/src/App.tsx
  frontend/src/components/store/Star/index.tsx
  frontend/src/components/store/detail/DetailImageList.tsx
  frontend/src/components/store/detail/DetailTable.tsx
  frontend/src/mocks/data/foodDetail.json
  frontend/src/pages/Store/Detail.tsx
  frontend/src/utils/tableData.ts
Labels: FE, feat

#16 [feat] Type, 더미데이터 추가 및 세부 카테고리 분류 초기구현
  frontend/src/assets/types/CategoryType.tsx
  frontend/src/assets/types/ProductType.tsx
  frontend/src/mocks/data/food.json
  frontend/src/mocks/data/supplement.json
  frontend/src/pages/Store/index.tsx
Labels: FE, feat

#20 feat: 카카오 로그인 api 추가
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/strategies/accessToken.strategy.ts
  backend/src/auth/strategies/refreshToken.strategy.ts
  backend/src/configs/typeorm.config.ts
  backend/src/entity/cart.entity.ts
  backend/src/user/user.controller.spec.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.spec.ts
  backend/src/user/user.service.ts
  frontend/.yarn/install-state.gz
  frontend/src/App.tsx
  frontend/src/pages/Login.tsx
Labels: BE, feat

#21 [fix] entity type 수정
  backend/src/entity/allergy.entity.ts
  backend/src/entity/base.entity.ts
  backend/src/entity/cart.entity.ts
  backend/src/entity/cart.product.entity.ts
  backend/src/entity/food.entity.ts
  backend/src/entity/health.entity.ts
  backend/src/entity/order.entity.ts
  backend/src/entity/orderItem.entity.ts
  backend/src/entity/pet.entity.ts
  backend/src/entity/product.entity.ts
  backend/src/entity/productReview.entity.ts
  backend/src/entity/snack.entity.ts
  backend/src/entity/supplement.entity.ts
  backend/src/entity/user.entity.ts
Labels: BE, fix

#22 [feat] StickyFooter&ProductHorizontal Component, 결제페이지 UI
  frontend/public/svgs/check.svg
  frontend/src/App.tsx
  frontend/src/assets/images/svgs/Check.jsx
  frontend/src/assets/images/svgs/index.jsx
  frontend/src/components/store/Product/ProductHorizontal.stories.tsx
  frontend/src/components/store/Product/ProductHorizontal.tsx
  frontend/src/components/store/Select/Select.stories.tsx
  frontend/src/components/store/Select/index.tsx
  frontend/src/components/store/StickyFooter/StickyFooter.stories.tsx
  frontend/src/components/store/StickyFooter/index.tsx
  frontend/src/pages/Payment/index.tsx
Labels: FE, feat

#23 [feat] 상품 상세 페이지 후기 컴포넌트 구현
  frontend/public/svgs/defaultProfile.svg
  frontend/src/assets/images/svgs/DefaultProfile.jsx
  frontend/src/assets/images/svgs/index.jsx
  frontend/src/assets/types/ReviewType.ts
  frontend/src/components/common/Layout/index.tsx
  frontend/src/components/store/Hr/index.tsx
  frontend/src/components/store/Product/index.tsx
  frontend/src/components/store/Star/index.tsx
  frontend/src/components/store/detail/DetailButton.tsx
  frontend/src/components/store/detail/DetailImageList.tsx
  frontend/src/components/store/detail/DetailTable.tsx
  frontend/src/components/store/detail/ProductReview.tsx
  frontend/src/components/store/detail/ProductReviewItem.tsx
  frontend/src/components/store/detail/ReviewStats.tsx
  frontend/src/components/store/detail/ReviewText.tsx
  frontend/src/mocks/data/review.json
  frontend/src/pages/Store/Detail.tsx
  frontend/src/styles/colors.ts
  frontend/src/utils/scoreCounts.ts
Labels: FE, feat

#24 [feat] 초기 데이터 추가, entity 수정, product DTO 추가
  backend/.gitignore
  backend/src/app.module.ts
  backend/src/entity/pet.entity.ts
  backend/src/product/dto/food.dto.ts
  backend/src/product/dto/snack.dto.ts
  backend/src/product/dto/supplement.dto.ts
  backend/src/product/product.controller.ts
  backend/src/product/product.module.ts
  backend/src/product/product.service.ts
Labels: BE, feat

#27 [feat] Tag Component 생성
  frontend/src/components/common/Tag/Tag.stories.tsx
  frontend/src/components/common/Tag/index.tsx
  frontend/src/components/common/Typo/index.tsx
  frontend/src/pages/Store/index.tsx
  frontend/src/styles/tag.ts
  frontend/src/styles/theme.ts
  frontend/src/styles/typo.tsx
  frontend/tsconfig.json
Labels: FE, fix, feat

#30 [feat] mypage 유저 정보 조회 및 DB 저장
  backend/src/app.module.ts
  backend/src/auth/auth.service.ts
  backend/src/entity/pet.entity.ts
  backend/src/entity/user.entity.ts
  backend/src/mypage/dto/getUserResponse.dto.ts
  backend/src/mypage/mypage.controller.ts
  backend/src/mypage/mypage.module.ts
  backend/src/mypage/mypage.service.ts
Labels: BE, feat

#36 [feat] product list 및 detail product api 추가(LUP-63)
  backend/src/entity/allergy.entity.ts
  backend/src/entity/cart.entity.ts
  backend/src/entity/cart.product.entity.ts
  backend/src/entity/food.entity.ts
  backend/src/entity/order.entity.ts
  backend/src/entity/orderItem.entity.ts
  backend/src/entity/pet.entity.ts
  backend/src/entity/product.entity.ts
  backend/src/entity/productReview.entity.ts
  backend/src/entity/snack.entity.ts
  backend/src/entity/supplement.entity.ts
  backend/src/entity/user.entity.ts
  backend/src/product/product.controller.ts
  backend/src/product/product.module.ts
  backend/src/product/product.service.ts
Labels: BE, refactor, feat

#39 [feat] product list 및 detail product api 추가
  backend/src/entity/food.entity.ts
  backend/src/entity/snack.entity.ts
  backend/src/entity/supplement.entity.ts
  backend/src/product/product.controller.ts
  backend/src/product/product.service.ts
  backend/src/types/category.ts
Labels: BE, feat

#40 [refact] base entity 수정
  backend/src/entity/allergy.entity.ts
  backend/src/entity/base.entity.ts
  backend/src/entity/health.entity.ts
  backend/src/entity/pet.entity.ts
Labels: BE, refactor

#41 [chore] cart 페이지 컴포넌트 분할, Layout과 Navbar css 수정
  frontend/src/assets/types/CartType.tsx
  frontend/src/components/cart/CartCost/index.tsx
  frontend/src/components/cart/CartItem/index.tsx
  frontend/src/components/cart/Checkbox/index.tsx
  frontend/src/components/common/Layout/index.tsx
  frontend/src/components/common/Navbar/index.tsx
  frontend/src/components/store/detail/DetailButton.tsx
  frontend/src/mocks/data/cart.json
  frontend/src/pages/Cart/index.tsx
  frontend/src/pages/Store/Detail.tsx
  frontend/src/pages/Store/index.tsx
Labels: FE, chore

#42 [feat(be)] API요청, 유저의 펫 정보 조회
  backend/src/auth/auth.controller.ts
  backend/src/configs/setupSwagger.ts
  backend/src/configs/typeorm.config.ts
  backend/src/entity/allergy.entity.ts
  backend/src/entity/user.entity.ts
  backend/src/mypage/dto/getUserResponse.dto.ts
  backend/src/mypage/dto/updatePet.dto.ts
  backend/src/mypage/mypage.controller.ts
  backend/src/mypage/mypage.module.ts
  backend/src/mypage/mypage.service.ts
Labels: BE, refactor, feat

#43 [feat(be)] mypage정보 수정 API 구현
  backend/src/mypage/dto/updatePet.dto.ts
  backend/src/mypage/dto/updatePetRequest.dto.ts
  backend/src/mypage/mypage.controller.ts
  backend/src/mypage/mypage.service.ts
Labels: BE, feat

#46 [feat] search api 추가
  backend/src/entity/allergy.entity.ts
  backend/src/product/product.controller.ts
  backend/src/product/product.service.ts
Labels: BE, feat

#45 [fix] MobileWrapper css 수정, reviewHistory page route 추가
  frontend/src/App.tsx
  frontend/src/components/common/Layout/index.tsx
  frontend/src/pages/Mypage/Review.tsx
Labels: FE, fix, chore

#47 [chore] detail, cart 페이지 UI 수정 및 후기 컴포넌트 스크롤 구현
  frontend/src/components/store/detail/DetailButton.tsx
  frontend/src/components/store/detail/DetailImageList.tsx
  frontend/src/components/store/detail/ProductReview.tsx
  frontend/src/components/store/detail/ProductReviewItem.tsx
  frontend/src/pages/Cart/index.tsx
  frontend/src/pages/Search/index.tsx
  frontend/src/pages/Store/Detail.tsx
Labels: FE, chore
